import {defaultSelection,validateSelection,equipment,cost,loadoutIssue,search,validateDatabase} from './core.js?v=equipment-3';
import {findCoreRule,resolveAbility} from './rules.js?v=equipment-3';
const $=s=>document.querySelector(s), E=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const key='field-reference.v1';let coreRules=[],referenceRules=[];let state={loadouts:[],collapsed:{},images:{}},db,activeFaction='astra-militarum',filter='All',legendFilter='all',catalogueQuery='',draft=null,view='all',cataloguePage=1;
try {const saved=JSON.parse(localStorage.getItem(key));if(saved&&Array.isArray(saved.loadouts))state={...state,...saved};}catch{notify('Saved settings could not be read. You can still browse.');}
function notify(s){$('#notice').textContent=s;}
function persist(){try{localStorage.setItem(key,JSON.stringify(state));return true;}catch{notify('Browser storage is unavailable or full. Export a backup before closing.');return false;}}
function src(u){return db.sources.find(s=>s.id===u.sourceId);}
function sourceLink(u,label='Read source ↗'){return `<a href="${E(src(u).url)}" target="_blank" rel="noopener noreferrer">${E(label)}</a>`;}
function badge(u){if(u.dataStatus==='requires-verification')return '<span class="badge legend">REQUIRES VERIFICATION'+(u.legends?' · LEGENDS':'')+'</span>';return `<span class="badge ${u.legends?'legend':''}">${u.legends?('LEGENDS'+(u.edition!==11?' · EDITION '+u.edition:'')):'11TH EDITION'}</span>`;}
function photo(u){const image=state.images[u.id]||u.image?.path;return image?`<img src="${E(image)}" alt="${E(u.name)}" loading="lazy">`:`<div class="no-image"><span class="image-glyph">＋</span><span>UNIT IMAGE NEEDED</span><small>Add your miniature photo on the datasheet</small></div>`;}
function select(id,label,values,value){return `<label>${label}<select id="${id}">${values.map(([v,n])=>`<option value="${E(v)}" ${v===value?'selected':''}>${E(n)}</option>`).join('')}</select></label>`;}
function catalogue(){
 const faction=db.factions.find(f=>f.id===activeFaction),units=db.units.filter(u=>u.factionId===activeFaction),shown=units.filter(u=>(filter==='All'||u.keywords.includes(filter))&&(legendFilter==='all'||(legendFilter==='unverified'?u.dataStatus==='requires-verification':u.legends===(legendFilter==='legends')))&&u.name.toLowerCase().includes(catalogueQuery.toLowerCase()));
 const cats=['All',...new Set(units.flatMap(u=>u.keywords).filter(k=>['VEHICLE','CHARACTER','INFANTRY','BATTLELINE','MOUNTED','ARTILLERY','TRANSPORT','DEDICATED TRANSPORT','AIRCRAFT','WALKER','FORTIFICATION','MONSTER','TITANIC','SWARM'].includes(k)))];
 const pages=Math.max(1,Math.ceil(shown.length/48));cataloguePage=Math.min(cataloguePage,pages);const slice=shown.slice((cataloguePage-1)*48,cataloguePage*48);
 $('#main').innerHTML=`<section class="hero"><div><p class="eyebrow">THE FIELD ARCHIVE / ${db.factions.length} FACTIONS</p><h1>${E(faction.name)}</h1><p class="subtitle">${db.units.length.toLocaleString()} catalogue entries across your approved sources.</p></div><div class="hero-meta"><strong>${units.length}</strong><span>FACTION ENTRIES<br>${units.filter(u=>u.legends).length} LEGENDS</span></div></section><div class="status-strip">Source-extracted profiles · ${units.filter(u=>u.dataStatus==='requires-verification').length} entries require verification · core rules included <a href="#audit">View coverage →</a></div><div class="toolbar">${select('faction','Faction',db.factions.map(f=>[f.id,f.name+' ('+(f.unitCount||0)+')']),activeFaction)}<label>Find a unit<input id="unit-search" type="search" placeholder="Search this catalogue" value="${E(catalogueQuery)}"></label>${select('legends','Show',[['all','All entries'],['standard','Non-Legends'],['legends','Legends only'],['unverified','Requires verification']],legendFilter)}</div><div class="filter-row" role="group" aria-label="Keyword filters">${cats.map(c=>`<button data-filter="${E(c)}" aria-pressed="${filter===c}" class="chip ${filter===c?'selected':''}">${c==='All'?'All units':E(c.toLowerCase())}</button>`).join('')}<span>${shown.length} matches</span></div><section class="cards" aria-label="Unit catalogue">${slice.map(u=>`<a class="card" href="#unit/${u.id}"><div class="card-image">${photo(u)}${badge(u)}</div><div class="card-body"><p class="eyebrow">${E(u.category||'Unit')}</p><h2>${E(u.name)} <span>↗</span></h2><p>${u.dataStatus==='requires-verification'?'Stats withheld pending verification':u.weapons.length+' weapon profiles · '+u.profiles.length+' model profile'+(u.profiles.length===1?'':'s')}</p></div></a>`).join('')||'<div class="empty"><h2>No matching units</h2><p>Try another filter or search.</p></div>'}</section><div class="pagination"><button id="previous-page" ${cataloguePage===1?'disabled':''}>← Previous</button><span>Page ${cataloguePage} of ${pages} · ${shown.length?((cataloguePage-1)*48+1):0}–${Math.min(cataloguePage*48,shown.length)} of ${shown.length}</span><button id="next-page" ${cataloguePage===pages?'disabled':''}>Next →</button></div>`;
 $('#faction').onchange=e=>{activeFaction=e.target.value;filter='All';legendFilter='all';catalogueQuery='';cataloguePage=1;location.hash='#catalogue/'+activeFaction;};$('#legends').onchange=e=>{legendFilter=e.target.value;cataloguePage=1;catalogue();};$('#unit-search').oninput=e=>{const p=e.target.selectionStart;catalogueQuery=e.target.value;cataloguePage=1;catalogue();$('#unit-search').focus();$('#unit-search').setSelectionRange(p,p);};document.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{filter=b.dataset.filter;cataloguePage=1;catalogue();});
 $('#previous-page').onclick=()=>{cataloguePage--;catalogue();window.scrollTo(0,0);};$('#next-page').onclick=()=>{cataloguePage++;catalogue();window.scrollTo(0,0);};
}

function ruleParagraphs(text){return (text||'').split(/\n\n+/).map(p=>`<p>${E(p)}</p>`).join('');}
function pdfLink(page,label){return `<a href="core-rules.pdf#page=${page}" target="_blank" rel="noopener noreferrer">${E(label||'Core Rules · p. '+page)} ↗</a>`;}
function coreBody(r){return ruleParagraphs(r.text)+`<p class="rule-source">Uploaded Core Rules · §${E(r.section)} · ${pdfLink(r.page)}${r.relatedPages?.length?' · Related: '+r.relatedPages.map(p=>pdfLink(p,'p. '+p)).join(' · '):''}</p>`;}
function weaponTrait(u,name,weapon){const c=u.edition===11?findCoreRule(coreRules,name):null;const ref=weapon.abilityReferences?.[name];return c?`<button type="button" class="trait-button" data-core="${E(c.id)}" data-rule-label="${E(name)}">${E(name)}</button>`:ref?`<button type="button" class="trait-button" data-glossary="${E(ref)}">${E(name)}</button>`:`<span>${E(name)}</span>`;}
function abilityMarkup(u,a){const resolved=resolveAbility(coreRules,referenceRules,u,a);let body;
 if(resolved?.type==='core')body=coreBody(resolved.rule);
 else if(resolved?.type==='reference')body=resolved.rule.html+`<p class="rule-source">Uploaded faction rules · <a href="${E(resolved.rule.sourceUrl)}" target="_blank" rel="noopener noreferrer">Source ↗</a></p>`;
 else if(a.text)body=(a.html||ruleParagraphs(a.text))+`<p class="rule-source">${E(a.textSource||'Imported rule')} · ${sourceLink(u)}</p>`;
 else body=`<p class="hint">Faction-specific text has not been supplied for this entry.</p>${sourceLink(u,'Read ability ↗')}`;
 return `<details class="rule" id="rule-${E(a.id)}" ${resolved?.type==='unit'?'open':''}><summary>${E(a.name)} <span class="chevron">⌄</span></summary><div class="rule-content">${body}</div></details>`;
}
function showRule(id,type,label){const r=(type==='core'?coreRules:referenceRules).find(r=>r.id===id);if(!r)return;
 let dialog=document.getElementById('rule-dialog');if(!dialog){dialog=document.createElement('dialog');dialog.id='rule-dialog';dialog.className='rule-dialog';document.body.append(dialog);dialog.addEventListener('click',e=>{if(e.target===dialog)dialog.close();});}
 dialog.innerHTML=`<div class="dialog-header"><h2 id="dialog-title">${E(label||r.name)}</h2><button type="button" id="close-rule" aria-label="Close rule">×</button></div><div class="dialog-body">${type==='core'?coreBody(r):r.html+`<p class="rule-source">Uploaded faction reference · <a href="${E(r.sourceUrl)}" target="_blank" rel="noopener noreferrer">Source ↗</a></p>`}</div>`;dialog.setAttribute('aria-labelledby','dialog-title');dialog.querySelector('#close-rule').onclick=()=>dialog.close();if(!dialog.open)dialog.showModal();dialog.scrollTop=0;
}
document.addEventListener('click',e=>{const b=e.target.closest('[data-core],[data-glossary]');if(b){e.preventDefault();showRule(b.dataset.core||b.dataset.glossary,b.dataset.core?'core':'reference',b.dataset.ruleLabel);}});
function corePage(){ $('#main').innerHTML=`<p class="eyebrow">YOUR UPLOADED RULEBOOK</p><h1>Core abilities</h1><p class="subtitle">Click an ability for its full description. Weapon keywords on datasheets open the same reference.</p><p>${pdfLink(1,'Open complete rulebook')}</p><div class="core-rule-list">${coreRules.filter(r=>r.id!=='scout-move').map(r=>`<button data-core="${E(r.id)}">${E(r.name)} <small>§${E(r.section)} · p. ${r.page}</small></button>`).join('')}</div>`;}

function equipmentRulesMarkup(u){const r=u.equipmentRules;if(!r)return '';return `<details class="rule equipment-rules" id="equipment-rules" open><summary>Equipment & weapon options <span class="chevron">⌄</span></summary><div class="rule-content"><h3>Default equipment</h3><div>${r.defaultHtml}</div><h3>Wargear options & restrictions</h3><div>${r.optionsHtml||'<p>No wargear-options section is listed in the supplied datasheet.</p>'}</div><p class="rule-source">Uploaded datasheet · ${sourceLink(u)}</p></div></details>`;}
function pointsRows(u){let group='';return (u.points.rows||[]).map(r=>{const heading=group!==r.group?`<h3 class="points-group">${E(r.group)}</h3>`:'';group=r.group;return heading+`<div><span>${E(r.label)}</span><strong>${E(r.value)}</strong></div>`;}).join('')||'<p class="hint">Points require verification; see source.</p>';}
function compactWeaponTable(u,kind,visible,counts){
 const rows=visible.filter(w=>w.kind===kind);
 return `<div class="weapon-table-wrap" tabindex="0" role="region" aria-label="Scrollable weapon statistics"><table class="weapon-table"><caption class="sr-only">${kind==='ranged'?'Ranged':'Melee'} weapon profiles</caption><colgroup><col class="name-col">${'<col class="stat-col">'.repeat(6)}<col class="toggle-col"></colgroup><thead><tr><th scope="col">${kind==='ranged'?'Ranged':'Melee'} weapons</th><th scope="col">Range</th><th scope="col">A</th><th scope="col">${kind==='melee'?'WS':'BS'}</th><th scope="col">S</th><th scope="col">AP</th><th scope="col">D</th><th scope="col"><span class="sr-only">Visibility</span></th></tr></thead><tbody>${rows.map(w=>{const hidden=!!state.collapsed[u.id+'/'+w.id];return `<tr id="weapon-${w.id}" class="weapon-row ${hidden?'is-collapsed':''}"><th scope="row"><span class="weapon-name">${view==='mine'?`<b class="quantity">${counts[w.equipmentId]}×</b> `:''}${E(w.name)}</span><span class="inline-traits" ${hidden?'hidden':''}>${w.abilityNames.map(a=>weaponTrait(u,a,w)).join('')}</span></th>${Object.entries(w.stats).map(([k,v])=>`<td><span class="weapon-stat" ${hidden?'hidden':''}>${E(v)}</span></td>`).join('')}<td class="toggle-cell"><button class="weapon-toggle" data-collapse="${u.id}/${w.id}" aria-expanded="${!hidden}" aria-label="${hidden?'Show':'Hide'} ${E(w.name)} statistics" title="${hidden?'Show':'Hide'} weapon statistics">${hidden?'＋':'−'}</button></td></tr>`;}).join('')||'<tr><td colspan="8">No imported profiles in this section.</td></tr>'}</tbody></table></div>`;
}
function setWeaponVisibility(button,show){
 const row=button.closest('tr');row.classList.toggle('is-collapsed',!show);row.querySelectorAll('.weapon-stat,.inline-traits').forEach(el=>el.hidden=!show);
 button.setAttribute('aria-expanded',String(show));button.textContent=show?'−':'＋';button.setAttribute('aria-label',(show?'Hide ':'Show ')+row.querySelector('.weapon-name').textContent.trim()+' statistics');button.title=(show?'Hide':'Show')+' weapon statistics';state.collapsed[button.dataset.collapse]=!show;
}
function unitPage(u,targetType,targetId){
 if(draft?.unitId===u.id && $('.loadout-editor'))draft.editorOpen=$('.loadout-editor').open;
 const faction=db.factions.find(f=>f.id===u.factionId);activeFaction=u.factionId;
 const configurable=validateSelection(u,defaultSelection(u)).length===0;
 if(targetType==='weapon'||!configurable)view='all';
 if(!draft||draft.unitId!==u.id)draft={unitId:u.id,selection:defaultSelection(u),name:'My '+u.name,ordinal:1};
 const counts=equipment(u,draft.selection),price=cost(u,draft.selection,draft.ordinal);const visible=u.weapons.filter(w=>view==='all'||counts?.[w.equipmentId]);
 $('#main').classList.add('datasheet-page');
 $('#main').innerHTML=`<a class="back" href="#catalogue/${u.factionId}">← ${E(faction.name)} catalogue</a>
 <section class="unit-heading"><div><div class="unit-title-line"><h1>${E(u.name)}</h1>${badge(u)}</div>
 <div class="model-profiles">${u.profiles.map(p=>`<div class="model-profile">${u.profiles.length>1?`<span class="model-label">${E(p.name)}</span>`:''}<div class="profile">${Object.entries(p.characteristics).map(([k,v])=>`<div><small>${E(k)}</small><strong>${E(v)}</strong></div>`).join('')}</div></div>`).join('')||'<p class="warning">11TH EDITION DATA NOT VERIFIED</p>'}</div>${u.invulnerable?.values?.length?`<p class="invulnerable">Invulnerable save: <b>${u.invulnerable.values.map(E).join(' / ')}</b> · check source for eligible models and conditions</p>`:''}
 <p class="keywords">${u.keywordGroups?.length>1?'Keywords include model-specific entries · ':''}${u.keywords.map(E).join(' · ')}</p></div>
 <div class="unit-image">${photo(u)}<label class="photo-upload">${state.images[u.id]?'Change photo':'Add photo'}<input id="photo" type="file" accept="image/png,image/jpeg,image/webp"></label>${state.images[u.id]?'<button id="remove-photo" class="photo-remove">Remove</button>':''}</div></section>
 ${u.dataStatus==='requires-verification'?'<p class="warning">'+u.issues.map(E).join(' · ')+'. Numerical profiles withheld.</p>':u.edition!==11?'<p class="warning">Legacy Legends · Edition '+E(u.edition)+' · 11th Edition data not verified.</p>':''}
 <div class="status-strip"><span>${u.abilityImportStatus==='imported'?'Ability text imported · click highlighted rules for details':'Core ability descriptions included · faction text remains linked'}</span>${sourceLink(u)}</div>
 <div class="sheet-grid"><section class="weapons-column"><div class="weapons-top"><div class="segmented"><button id="all" aria-pressed="${view==='all'}">All weapons (${u.weapons.length})</button><button id="mine" ${!configurable?'disabled title="Equipment restrictions have not been validated for this unit"':''} aria-pressed="${view==='mine'}">My loadout</button></div><div class="small-actions"><button id="expand">Show all</button><button id="collapse">Hide all</button></div></div>
 <p class="mobile-table-hint">Swipe the table sideways to see every stat. Hide/show stays on the right.</p>${['ranged','melee'].map(kind=>compactWeaponTable(u,kind,visible,counts)).join('')}
 <p class="hint profile-note">Alternative firing profiles share one equipped weapon; quantities count guns, not firing modes.</p>
 ${configurable?`<details class="loadout-editor" ${draft.editorOpen?'open':''}><summary>Configure & save loadout <span class="editor-price">${price??'—'} pts <span class="chevron">⌄</span></span></summary><div class="loadout-panel"><label class="loadout-name-field">Loadout name<input id="loadout-name" maxlength="80" value="${E(draft.name)}"></label>${u.wargear.slots.map(slot=>`<label>${E(slot.label)}<select data-slot="${slot.id}">${slot.options.map(o=>`<option value="${o.id}" ${draft.selection[slot.id]===o.id?'selected':''}>${E(o.label)}</option>`).join('')}</select></label>`).join('')}<label>Copy number in army<input id="ordinal" type="number" min="1" step="1" value="${draft.ordinal}"></label><div class="loadout-save"><button class="primary" id="save">Save loadout</button><span id="saved-feedback" aria-live="polite"></span></div><p class="hint loadout-price-note">Equipment costs included. Points publication date unverified; army legality not checked.</p></div></details>`:`<div class="unverified-loadout"><strong>Equipment reference</strong><p>${u.equipmentRules?'Default equipment, swaps and restrictions are listed below.':'Use the source link to check equipment restrictions.'} Automatic loadout validation is not available for this unit.</p>${u.equipmentRules?'':sourceLink(u,'Check equipment restrictions ↗')}</div>`}
 ${equipmentRulesMarkup(u)}</section><aside class="rules-column"><h2 class="section-bar">Abilities & rules</h2>${u.abilities.map(a=>abilityMarkup(u,a)).join('')}
 ${(u.ruleSections||[]).map(r=>`<details class="rule" id="section-${E(r.id)}"><summary>${E(r.name)} <span class="chevron">⌄</span></summary><div class="rule-content">${r.html}<p class="rule-source">Uploaded datasheet · ${sourceLink(u)}</p></div></details>`).join('')}<h2 class="section-bar">Unit composition</h2><p class="composition">${u.composition.entries?.length?u.composition.entries.map(E).join('<br>'):u.composition.models.map(m=>`${m.minimum} × ${E(m.name)}`).join(', ')||'Composition requires verification.'}</p>
 <h2 class="section-bar">Points from source</h2><div class="points-rows">${pointsRows(u)}</div>
 <p class="hint">${configurable?'Configured model: '+price+' pts. ':''}Publication date not verified. Check any model-count, equipment and unit-copy conditions above.</p>
 <details class="rule provenance"><summary>Source & verification <span class="chevron">⌄</span></summary><div class="rule-content"><p>${E(src(u).publication)} · retrieved ${E(src(u).retrievedAt||src(u).verifiedAt)}</p><p>Approved secondary source; official PDF cross-check pending.</p>${sourceLink(u)}<p>Remaining checks: ${u.missing.map(E).join('; ')}.</p></div></details>
 </aside></div><div class="faction-keywords">${(u.keywordGroups||[]).map(g=>`<p><b>${E(g.scope)}</b> ${g.values.map(E).join(' · ')}</p>`).join('')}<b>FACTION KEYWORDS</b> ${u.factionKeywords.map(E).join(', ')}</div>`;
 $('#all').onclick=()=>{view='all';unitPage(u);};$('#mine').onclick=()=>{view='mine';unitPage(u);};
 document.querySelectorAll('[data-slot]').forEach(el=>el.onchange=()=>{draft.selection[el.dataset.slot]=el.value;unitPage(u);});
 if(configurable){$('#loadout-name').oninput=e=>{draft.name=e.target.value;};$('#ordinal').onchange=e=>{draft.ordinal=Number(e.target.value);unitPage(u);};
 $('#save').onclick=()=>{const errors=validateSelection(u,draft.selection);if(!draft.name.trim())errors.push('Give this loadout a name.');if(price===null)errors.push('Copy number must be a positive whole number.');if(errors.length){notify(errors.join(' '));return;}const record={id:draft.id||crypto.randomUUID(),unitId:u.id,revision:u.revision,name:draft.name.trim(),ordinal:draft.ordinal,selection:{...draft.selection}};state.loadouts=state.loadouts.filter(l=>l.id!==record.id);state.loadouts.push(record);draft.id=record.id;if(persist())$('#saved-feedback').textContent='Saved in this browser.';};
 }
 document.querySelectorAll('[data-collapse]').forEach(el=>el.onclick=()=>{setWeaponVisibility(el,el.getAttribute('aria-expanded')!=='true');persist();});
 for(const [id,show] of [['expand',true],['collapse',false]])$('#'+id).onclick=()=>{document.querySelectorAll('[data-collapse]').forEach(b=>setWeaponVisibility(b,show));persist();};

 $('#photo').onchange=async e=>{const f=e.target.files[0];if(!f)return;if(!['image/png','image/jpeg','image/webp'].includes(f.type)||f.size>8*1024*1024){notify('Choose a PNG, JPEG or WebP smaller than 8 MB.');return;}try{const bitmap=await createImageBitmap(f),canvas=document.createElement('canvas'),scale=Math.min(1,900/Math.max(bitmap.width,bitmap.height));canvas.width=bitmap.width*scale;canvas.height=bitmap.height*scale;canvas.getContext('2d').drawImage(bitmap,0,0,canvas.width,canvas.height);bitmap.close();state.images[u.id]=canvas.toDataURL('image/webp',.8);if(persist()){notify('Unit photo saved in this browser.');unitPage(u);}}catch{notify('This photo could not be read.');}};
 if($('#remove-photo'))$('#remove-photo').onclick=()=>{delete state.images[u.id];persist();unitPage(u);};
 if(targetId){const el=document.getElementById(targetType+'-'+targetId);if(el){if(targetType==='weapon'){setWeaponVisibility(el.querySelector('[data-collapse]'),true);persist();}else el.open=true;el.scrollIntoView({block:'center'});el.classList.add('highlight');}}
}
function savedPage(){
 $('#main').innerHTML=`<p class="eyebrow">YOUR COLLECTION</p><h1>My loadouts</h1><p class="subtitle">Saved on this browser. Export a backup to keep a portable copy.</p><div class="small-actions"><button id="export">Export backup</button><label class="button">Import backup<input id="import" type="file" accept="application/json" hidden></label></div><div class="saved-list">${state.loadouts.map(l=>{const u=db.units.find(u=>u.id===l.unitId),issues=loadoutIssue(u,l);return `<article class="saved-card"><div><h2>${E(l.name)}</h2><p>${E(u?.name||l.unitId)} · ${issues.length?'Needs review':cost(u,l.selection,l.ordinal)+' pts'}${u?.legends?' · LEGENDS':''}</p>${issues.length?`<p class="warning">${issues.map(E).join(' ')}</p>`:''}</div><div class="small-actions"><button data-open="${E(l.id)}">${issues.length?'Review':'Open'}</button><button data-copy="${E(l.id)}">Duplicate</button><button data-delete="${E(l.id)}">Delete</button></div></article>`}).join('')||'<div class="empty"><h2>No saved loadouts yet</h2><p>Open a datasheet to configure your first model.</p><a href="#catalogue">Browse units →</a></div>'}</div>`;
 document.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>{const l=state.loadouts.find(l=>l.id===b.dataset.open),u=db.units.find(u=>u.id===l.unitId);if(!u){notify('This unit is not present in the current database.');return;}draft={...l,selection:loadoutIssue(u,l).length?defaultSelection(u):{...l.selection}};view='mine';location.hash='#unit/'+u.id;});
 document.querySelectorAll('[data-copy]').forEach(b=>b.onclick=()=>{const l=state.loadouts.find(l=>l.id===b.dataset.copy);state.loadouts.push({...structuredClone(l),id:crypto.randomUUID(),name:l.name+' (copy)'});persist();savedPage();});
 document.querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>{const selected=state.loadouts.find(l=>l.id===b.dataset.delete);if(confirm(`Delete “${selected.name}”?`)){state.loadouts=state.loadouts.filter(l=>l.id!==selected.id);persist();savedPage();}});
 $('#export').onclick=()=>{const blob=new Blob([JSON.stringify({format:'field-reference-backup',version:1,...state},null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='field-reference-backup.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);};
 $('#import').onchange=async e=>{try{const f=e.target.files[0];if(!f)return;if(f.size>8*1024*1024)throw Error('Backup is too large.');const b=JSON.parse(await f.text());if(b.format!=='field-reference-backup'||b.version!==1||!Array.isArray(b.loadouts))throw Error('Not a supported backup.');for(const l of b.loadouts){const u=db.units.find(u=>u.id===l.unitId);if(typeof l.name!=='string'||typeof l.id!=='string'||!u||validateSelection(u,l.selection).length||!Number.isInteger(l.ordinal)||l.ordinal<1)throw Error('Backup contains an invalid or unavailable loadout.');}const images=b.images||{};for(const [id,value] of Object.entries(images))if(!db.units.some(u=>u.id===id)||typeof value!=='string'||!/^data:image\/(png|jpeg|webp);base64,[A-Za-z0-9+/=]+$/.test(value))throw Error('Invalid image in backup.');const seen=new Set(state.loadouts.map(l=>l.id));for(const l of b.loadouts)state.loadouts.push({...l,id:seen.has(l.id)?crypto.randomUUID():l.id});state.images={...state.images,...images};if(persist())notify('Backup merged. Existing loadouts retained.');savedPage();}catch(err){notify('Import failed: '+err.message);}};
}
function audit(){
 const pending=db.units.filter(u=>u.dataStatus==='requires-verification');
 $('#main').innerHTML=`<p class="eyebrow">PROVENANCE / COVERAGE</p><h1>Sources & coverage</h1><p class="subtitle">Imported 5 October 2026 from your 23 approved faction sources.</p><div class="audit-grid"><article><strong>${db.units.length}</strong><p>Catalogue entries</p></article><article><strong>${db.units.reduce((n,u)=>n+u.weapons.length,0)}</strong><p>Weapon profiles</p></article><article><strong>${db.units.filter(u=>u.legends).length}</strong><p>Legends entries</p></article><article><strong>${pending.length}</strong><p>Require verification</p></article></div><section class="audit-section"><h2>What this covers</h2><p>Source-listed names, publication markers, model characteristics, weapon statistics, keyword scopes, composition counts and displayed points. Each record links to its exact source entry. The import checks structure and completeness; it is not an independent official rules audit.</p><p>Core ability descriptions come from your uploaded PDF. Necron and Astra Militarum ability text comes from your uploaded HTML files; other factions still have source links. Detachment selection and approved unit photos are not bundled. Equipment validation remains enabled only for the three previously reviewed single-model records. Missing current-edition evidence never becomes invented statistics or an inferred Legends label.</p><p>Records can recur across faction pages; catalogue totals are faction entries, not a deduplicated count of unique game units. Space Marine chapter keywords remain searchable.</p></section><div class="coverage-wrap"><table class="coverage-table"><thead><tr><th>Faction</th><th>Source entries</th><th>Imported</th><th>Legends</th><th>Flagged</th></tr></thead><tbody>${db.coverage.map(c=>`<tr><th><a href="#catalogue/${c.id}">${E(c.name)}</a></th><td>${c.sourceCards}</td><td>${c.imported}</td><td>${c.legends}</td><td>${c.unverified.length}</td></tr>`).join('')}</tbody></table></div><h2>Ability text coverage</h2><p>${(db.abilityCoverage||[]).map(c=>E(c.factionId)+': '+c.matched+' matched datasheets, '+c.abilities+' named ability descriptions, '+c.sections+' additional sections').join('<br>')}</p><p>Core definitions: ${coreRules.length} reference sections from your uploaded PDF. Datasheet-specific wording takes precedence over generic core definitions.</p><h2>Records needing verification</h2>${pending.map(u=>`<article class="source-row"><a href="#unit/${u.id}">${E(u.name)} · ${E(db.factions.find(f=>f.id===u.factionId).name)}</a><p>${u.issues.map(E).join('; ')}</p></article>`).join('')||'<p>No blocked numerical profiles.</p>'}<h2>Approved faction sources</h2><div class="source-list">${db.factions.map(f=>`<a href="${E(f.sourceUrl)}" target="_blank" rel="noopener noreferrer"><span>${E(f.name)}</span><small>${f.unitCount} source-listed entries</small><b>↗</b></a>`).join('')}</div>`;
}
function route(){$('#main').classList.remove('datasheet-page');const [page,id,type,target]=location.hash.slice(1).split('/');$('#search-results').hidden=true;notify('');if(page==='unit'){const u=db.units.find(u=>u.id===id);if(u)unitPage(u,type,target);else $('#main').innerHTML='<h1>Unit not found</h1><a href="#catalogue">Return to catalogue</a>';}else if(page==='saved')savedPage();else if(page==='audit')audit();else if(page==='core'){corePage();if(id)showRule(id,'core');}else if(page==='rule'){const r=db[id]?.find(x=>x.id===type);$('#main').innerHTML=r?`<h1>${E(r.name)}</h1><p>${E(r.text||'Full text not yet supplied.')}</p>`:'<h1>Rule not found</h1>';}else {if(page==='catalogue'&&id&&db.factions.some(f=>f.id===id)){if(activeFaction!==id){filter='All';legendFilter='all';catalogueQuery='';cataloguePage=1;}activeFaction=id;}catalogue();}document.querySelectorAll('nav a').forEach(a=>a.setAttribute('aria-current',a.hash===location.hash?'page':'false'));}
$('#search').oninput=e=>{if(!db)return;const q=e.target.value.trim().toLowerCase();const results=search(db,e.target.value);if(q)for(const r of coreRules)if((r.name+' '+r.text).toLowerCase().includes(q))results.push({name:r.name,kind:'Core rule',unit:'Uploaded rulebook',href:'#core/'+r.id});const box=$('#search-results');box.hidden=!e.target.value.trim();box.innerHTML=`<p>${results.length} matches across imported data</p>${results.slice(0,50).map(r=>`<a href="${E(r.href)}"><span>${E(r.name)}<small>${E(r.unit)}</small></span><b>${E(r.kind)}</b></a>`).join('')||'<p>No matching records have been imported.</p>'}`;box.querySelectorAll('a').forEach(a=>a.onclick=()=>{box.hidden=true;if(a.hash===location.hash)route();});};
document.addEventListener('keydown',e=>{if(e.key==='/'&&!['INPUT','TEXTAREA','SELECT'].includes(document.activeElement.tagName)){e.preventDefault();$('#search').focus();}if(e.key==='Escape')$('#search-results').hidden=true;});
document.addEventListener('click',e=>{if(!e.target.closest('#search-results,.global-search'))$('#search-results').hidden=true;});
window.addEventListener('hashchange',()=>{window.scrollTo(0,0);route();});
try{const r=await fetch('database.json?v=equipment-3');if(!r.ok)throw Error(`Database request failed (${r.status}).`);db=await r.json();const loaded=await Promise.all(['core-rules.json','reference-rules.json'].map(async f=>{const response=await fetch(f+'?v=equipment-3');if(!response.ok)throw Error('Missing rules file: '+f);return response.json();}));coreRules=loaded[0].rules;referenceRules=loaded[1].rules;const errors=validateDatabase(db);if(errors.length)throw Error(errors.join(' '));route();}catch(err){$('#main').innerHTML=`<h1>Database unavailable</h1><p>${E(err.message)}</p><p>Start the included local server with <code>python serve.py</code>, then open <a href="http://localhost:8080">http://localhost:8080</a>.</p>`;}
